spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prog5_probazh
    username: prog5_probazh
    password: 12345678
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
